[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
goblin = "0.3"
lazy_static = "1.4"
scroll = "0.10"
tar = "0.4"
zstd = "0.6"
