[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.72"
apple-sdk = "0.4.0"
bytes = "1.4.0"
clap = "4.3.19"
duct = "0.13.6"
flate2 = "1.0.26"
futures = "0.3.28"
goblin = "0.6.1"
hex = "0.4.3"
object = "0.31.1"
octocrab = { version = "0.19.0", features = ["rustls"] }
once_cell = "1.18.0"
rayon = "1.7.0"
reqwest = {version = "0.11.18", features = ["rustls"] }
scroll = "0.11.0"
semver = "1.0.18"
serde_json = "1.0.103"
serde = { version = "1.0.175", features = ["derive"] }
sha2 = "0.10.7"
tar = "0.4.39"
tempfile = "3.7.0"
text-stub-library = "0.9.0"
tokio = "1.29.1"
url = "2.4.0"
version-compare = "0.1.1"
zip = "0.6.6"
zstd = "0.12.4"
