[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
goblin = "0"
once_cell = "1"
scroll = "0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tar = "0"
version-compare = "0"
zstd = "0"

[dependencies.tugger-binary-analysis]
version = "0.1.0-pre"
git = "https://github.com/indygreg/PyOxidizer.git"
rev = "e86b2f46ed6b449bdb912900b0ac83576ad5ebe9"
