[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
apple-sdk = "0.4.0"
bytes = "1.4.0"
clap = "4.2.1"
duct = "0.13.6"
flate2 = "1.0.25"
futures = "0.3.28"
goblin = "0.6.1"
hex = "0.4.3"
object = "0.30.3"
octocrab = { version = "0.19.0", features = ["rustls"] }
once_cell = "1.17.1"
rayon = "1.7.0"
reqwest = {version = "0.11.16", features = ["rustls"] }
scroll = "0.11.0"
semver = "1.0.17"
serde_json = "1.0.95"
serde = { version = "1.0.159", features = ["derive"] }
sha2 = "0.10.6"
tar = "0.4.38"
tempfile = "3.5.0"
text-stub-library = "0.9.0"
tokio = "1.27.0"
url = "2.3.1"
version-compare = "0.1.1"
zip = "0.6.4"
zstd = "0.12.3"
