[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.71"
apple-sdk = "0.4.0"
bytes = "1.4.0"
clap = "4.2.7"
duct = "0.13.6"
flate2 = "1.0.26"
futures = "0.3.28"
goblin = "0.6.1"
hex = "0.4.3"
hyper = "0.14.26"
object = "0.31.0"
octocrab = { version = "0.21.0" }
once_cell = "1.17.1"
rayon = "1.7.0"
reqwest = {version = "0.11.17", features = ["rustls"] }
scroll = "0.11.0"
semver = "1.0.17"
serde_json = "1.0.96"
serde = { version = "1.0.162", features = ["derive"] }
sha2 = "0.10.6"
tar = "0.4.38"
tempfile = "3.5.0"
text-stub-library = "0.9.0"
tokio = "1.28.0"
url = "2.3.1"
version-compare = "0.1.1"
zip = "0.6.5"
zstd = "0.12.3"
