[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bytes = "1.1.0"
clap = "3.1.14"
duct = "0.13.5"
flate2 = "1.0.23"
futures = "0.3.21"
goblin = "0.5.1"
hex = "0.4.3"
object = "0.28.3"
octocrab = { version = "0.16.0", features = ["rustls"] }
once_cell = "1.10.0"
rayon = "1.5.2"
reqwest = {version = "0.11.10", features = ["rustls"] }
scroll = "0.11.0"
semver = "1.0.7"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
sha2 = "0.10.2"
tar = "0.4.38"
tempfile = "3.3.0"
# Waiting on 0.8 for a bug fix.
text-stub-library = { git = "https://github.com/indygreg/PyOxidizer.git", rev = "3468a52340fccc547c1d62456db570aeb0663d8e" }
tokio = "1.18.0"
tugger-apple = { git = "https://github.com/indygreg/PyOxidizer.git", rev = "3468a52340fccc547c1d62456db570aeb0663d8e" }
url = "2.2.2"
version-compare = "0.1.0"
zip = "0.6.2"
zstd = "0.10.0"
